baseurl                  = "https://marlongrunden.netlify.app"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Marlon Grunden // Composer"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics  = "UA-181752118-1"                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "Home"                           # What to call the home page link
    footerText           = "Marlon Grunden // Composer"

# Metadata for Open Graph and Twitter
    description          = "Marlon Grunden // Composer // Producer // Engineer"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Marlon Grunden // Composer"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "about"
    text = "Marlon Grunden"

[[params.mainMenu]]
    link = "listen"
    text = "Listen"

[[params.mainMenu]]
    link = "contact"
    text = "Contact"

#[[params.mainMenu]]
#    link = "blog"
#    text = "Blog"


[imaging]
    quality = 75
